version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: restaurant-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infraestructure/postgres/init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: restaurant-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./infraestructure/localstack/init-aws.sh:/docker-entrypoint-initaws.d/init-aws.sh"
    networks:
      - restaurant-network
    healthcheck:
      test: ["CMD", "awslocal", "sns", "list-topics"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

volumes:
  postgres_data:

networks:
  restaurant-network:
    driver: bridge